version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: 10.16.0
          npm-version: 6.9.0
      - run: node --version
  build-and-test:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build:prod
            - run: npm test:unit
workflows:
    build-and-test:
      jobs:
        - install-node
        - build-and-test
