version: 2.1
orbs:
  node: circleci/node@2.0.3
jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: 10.16.0
          npm-version: 6.9.0
      - run: node --version
  install-packages:
    executor:
      name: node/default
    steps:
      - node/install-packages

workflows:
    build-and-test:
      jobs:
        - install-node
        - install-packages
